// vb-study-data.jsx — Study Guide (스터디 가이드) content.
// VB_STUDY_CAT: per-category reflection / application / journal / prayer (theme-driven).
// VB_STUDY_VERSE: per-verse passage + context + key message (verse-specific).
// vbStudyGuide(verseId) merges them into a full guide.
// Exports: VB_STUDY_CAT, VB_STUDY_VERSE, vbStudyGuide

const VB_STUDY_CAT = {
  friendship: {
    reflectEn:['Who has shown steady friendship to you in a difficult season?','What kind of friend do you want to become for someone else?','Is there someone who may need your presence this week?'],
    reflectKo:['어려운 시기에 변함없이 곁에 있어준 사람은 누구인가요?','나는 누군가에게 어떤 친구가 되고 싶은가요?','이번 주에 내 곁이 필요한 사람은 누구일까요?'],
    applyEn:['Send a short message to a friend you appreciate.','Check in on someone who may be struggling.','Practice being present without trying to fix everything.','Remember one person who stood by you and thank them.'],
    applyKo:['고마운 친구에게 짧은 메시지를 보내보세요.','힘든 시간을 보내는 사람에게 안부를 물어보세요.','모든 문제를 해결하려 하기보다, 곁에 있어주는 연습을 해보세요.','내 곁을 지켜준 사람을 떠올리고 감사를 표현해보세요.'],
    journalEn:'Write about a time when someone’s steady presence helped you.',
    journalKo:'누군가의 변함없는 동행이 나에게 힘이 되었던 순간을 적어보세요.',
    prayerEn:'God, help me notice the people who have stood by me, and teach me to become a steady and loving presence for others. Amen.',
    prayerKo:'하나님, 제 곁을 지켜준 사람들을 기억하게 하시고, 저도 누군가에게 변함없고 따뜻한 동행이 되게 해주세요. 아멘.',
  },
  love: {
    reflectEn:['Where is patience hardest for you to practice in love?','Who in your life needs kindness rather than correction today?','What would it look like to love someone without keeping score?'],
    reflectKo:['사랑 안에서 오래 참기가 가장 어려운 곳은 어디인가요?','오늘 지적보다 친절이 더 필요한 사람은 누구인가요?','계산하지 않고 누군가를 사랑한다면 어떤 모습일까요?'],
    applyEn:['Choose patience in one small moment of irritation today.','Do a quiet act of kindness with no expectation of return.','Speak gently to someone you find difficult.'],
    applyKo:['오늘 짜증이 나는 작은 순간에 한 번 오래 참아보세요.','보답을 바라지 않는 작은 친절을 조용히 베풀어보세요.','대하기 어려운 사람에게 부드럽게 말해보세요.'],
    journalEn:'Write about a moment you received love you did not earn.',
    journalKo:'내가 받을 자격 없이 받은 사랑의 순간을 적어보세요.',
    prayerEn:'God, fill me with patient and kind love, so that I can give it away freely even when it is hard. Amen.',
    prayerKo:'하나님, 오래 참고 친절한 사랑으로 저를 채우셔서, 어려울 때에도 그 사랑을 값없이 나누게 해주세요. 아멘.',
  },
  family: {
    reflectEn:['What is one small way to bring peace to your home today?','Whose example shaped your sense of family?','What do you hope to pass on to those who come after you?'],
    reflectKo:['오늘 가정에 평안을 더할 작은 한 가지는 무엇일까요?','내 가족관을 형성해 준 사람은 누구인가요?','내 뒤를 잇는 사람들에게 무엇을 물려주고 싶나요?'],
    applyEn:['Say one encouraging thing to a family member today.','Forgive a small household frustration before it grows.','Make time for an unhurried moment at home.'],
    applyKo:['오늘 가족에게 격려의 말 한마디를 건네보세요.','집안의 작은 불만이 커지기 전에 먼저 풀어보세요.','집에서 서두르지 않는 시간을 잠시 가져보세요.'],
    journalEn:'Write about a moment of guidance or care you received at home.',
    journalKo:'가정에서 받은 돌봄이나 가르침의 순간을 적어보세요.',
    prayerEn:'God, make my home a place of care and guidance, and help me serve the people closest to me. Amen.',
    prayerKo:'하나님, 제 가정을 돌봄과 가르침의 자리가 되게 하시고, 가장 가까운 사람들을 섬기게 해주세요. 아멘.',
  },
  motivation: {
    reflectEn:['Where do you need strength to rise again today?','What has discouraged you, and what truth meets it?','What small, faithful step can you take right now?'],
    reflectKo:['오늘 다시 일어설 힘이 필요한 곳은 어디인가요?','무엇이 당신을 낙심하게 했고, 어떤 진리가 그것을 마주하나요?','지금 내디딜 수 있는 작고 신실한 한 걸음은 무엇인가요?'],
    applyEn:['Take one step toward something you have been avoiding.','Rest on purpose so you can endure for the long road.','Name your strength as a gift, not just your own effort.'],
    applyKo:['미뤄오던 일에 한 걸음 다가가 보세요.','긴 길을 견디기 위해 의도적으로 쉬어보세요.','내 힘을 나만의 노력이 아니라 선물로 여겨보세요.'],
    journalEn:'Write about a time you kept going when it was hard, and what carried you.',
    journalKo:'힘들었지만 계속 나아갔던 때와, 무엇이 나를 붙들어 주었는지 적어보세요.',
    prayerEn:'God, renew my strength when I am weary, and give me courage to take the next step. Amen.',
    prayerKo:'하나님, 지칠 때 새 힘을 주시고, 다음 한 걸음을 내딛을 용기를 주세요. 아멘.',
  },
  faith: {
    reflectEn:['Where are you being asked to trust without seeing the way?','What helps you keep faith when answers are slow?','What would it mean to walk by faith this week?'],
    reflectKo:['길이 보이지 않아도 신뢰해야 할 곳은 어디인가요?','응답이 더딜 때 믿음을 지키도록 돕는 것은 무엇인가요?','이번 주에 믿음으로 행한다는 것은 어떤 의미일까요?'],
    applyEn:['Bring one worry to God in honest prayer today.','Take a step of obedience before you feel certain.','Recall one past time God proved faithful.'],
    applyKo:['오늘 한 가지 염려를 솔직한 기도로 하나님께 맡겨보세요.','확신이 들기 전에 순종의 한 걸음을 내디뎌 보세요.','하나님이 신실하셨던 지난 한 순간을 떠올려보세요.'],
    journalEn:'Write about a time you had to trust before you understood.',
    journalKo:'이해하기 전에 먼저 신뢰해야 했던 때를 적어보세요.',
    prayerEn:'God, when I cannot see the way, help me trust You with all my heart. Amen.',
    prayerKo:'하나님, 길이 보이지 않을 때에도 마음을 다해 주님을 신뢰하게 해주세요. 아멘.',
  },
  forgiveness: {
    reflectEn:['Is there something you can begin to release today?','What makes forgiveness feel costly for you right now?','Where do you long to experience healing?'],
    reflectKo:['오늘 내려놓기 시작할 수 있는 것이 있나요?','지금 용서가 값비싸게 느껴지는 이유는 무엇인가요?','어디에서 회복을 경험하고 싶나요?'],
    applyEn:['Release one small grudge you have been holding.','Offer mercy to someone, including yourself.','Take one step toward a conversation you have avoided.'],
    applyKo:['붙들고 있던 작은 서운함 하나를 내려놓아 보세요.','누군가에게, 그리고 자신에게도 자비를 베풀어보세요.','피해온 대화를 향해 한 걸음 내디뎌 보세요.'],
    journalEn:'Write about something you are ready to begin letting go of.',
    journalKo:'이제 내려놓기 시작할 준비가 된 것을 적어보세요.',
    prayerEn:'God, help me let go and move toward healing, as I have been forgiven. Amen.',
    prayerKo:'하나님, 제가 용서받은 것처럼 내려놓고 회복을 향해 나아가게 해주세요. 아멘.',
  },
  gratitude: {
    reflectEn:['What small grace today do you not want to overlook?','When is it hardest for you to feel thankful?','Who could you thank this week?'],
    reflectKo:['오늘 무심코 지나치고 싶지 않은 작은 은혜는 무엇인가요?','감사를 느끼기 가장 어려운 때는 언제인가요?','이번 주에 감사를 전할 수 있는 사람은 누구인가요?'],
    applyEn:['Name three small graces before the day ends.','Thank someone specifically and out loud.','Pause to receive one ordinary moment with gratitude.'],
    applyKo:['하루가 끝나기 전에 작은 은혜 세 가지를 떠올려보세요.','누군가에게 구체적으로, 소리 내어 감사해보세요.','평범한 한 순간을 감사함으로 받아들이며 잠시 멈춰보세요.'],
    journalEn:'Write down three things you are grateful for today and why.',
    journalKo:'오늘 감사한 세 가지와 그 이유를 적어보세요.',
    prayerEn:'God, open my eyes to the grace already given, and make my heart thankful. Amen.',
    prayerKo:'하나님, 이미 주어진 은혜를 보게 하시고, 제 마음을 감사로 채워주세요. 아멘.',
  },
  hope: {
    reflectEn:['Where do you need to remember that your story is not over?','What future are you waiting for, and how do you wait well?','What small light can you look toward today?'],
    reflectKo:['당신의 이야기가 끝나지 않았음을 기억해야 할 곳은 어디인가요?','어떤 미래를 기다리고 있고, 어떻게 잘 기다릴 수 있을까요?','오늘 바라볼 수 있는 작은 빛은 무엇인가요?'],
    applyEn:['Write down one hope and keep it where you can see it.','Take one small action that points toward the future you hope for.','Encourage someone else who is waiting.'],
    applyKo:['소망 하나를 적어 눈에 보이는 곳에 두세요.','바라는 미래를 향한 작은 행동 하나를 해보세요.','함께 기다리는 누군가를 격려해보세요.'],
    journalEn:'Write about a hope you are holding onto, even quietly.',
    journalKo:'조용히라도 붙들고 있는 소망에 대해 적어보세요.',
    prayerEn:'God of hope, fill me with peace as I trust You, and remind me the story is not over. Amen.',
    prayerKo:'소망의 하나님, 주님을 신뢰하는 제게 평강을 채우시고, 이야기가 끝나지 않았음을 기억하게 해주세요. 아멘.',
  },
  wisdom: {
    reflectEn:['What choice today is asking for discernment?','Where might you be leaning on your own understanding alone?','Who could you ask for wise counsel?'],
    reflectKo:['오늘 분별이 필요한 선택은 무엇인가요?','내 명철만 의지하고 있는 곳은 어디인가요?','지혜로운 조언을 구할 수 있는 사람은 누구인가요?'],
    applyEn:['Pause before one decision and ask for wisdom.','Listen more than you speak in one conversation today.','Choose the patient option over the quick one.'],
    applyKo:['한 가지 결정을 앞두고 잠시 멈춰 지혜를 구해보세요.','오늘 한 대화에서 말하기보다 더 많이 들어보세요.','빠른 길보다 인내하는 길을 택해보세요.'],
    journalEn:'Write about a decision you are facing and what wisdom might look like.',
    journalKo:'지금 마주한 결정과, 지혜로운 선택은 어떤 모습일지 적어보세요.',
    prayerEn:'God, in all my ways help me acknowledge You, and make my paths straight. Amen.',
    prayerKo:'하나님, 제 모든 길에서 주님을 인정하게 하시고, 제 길을 곧게 인도해주세요. 아멘.',
  },
};

// Per-verse: surrounding passage + context + key message.
const VB_STUDY_VERSE = {
  v01:{ pRefEn:'Proverbs 17:15–18', pRefKo:'잠언 17:15–18',
    pEn:'Acquitting the guilty and condemning the innocent—the Lord detests them both. Why should fools have money to buy wisdom, when they are not able to understand it? A friend loves at all times, and a brother is born for a time of adversity. One who has no sense shakes hands in pledge and puts up security for a neighbor.',
    pKo:'악인을 의롭다 하고 의인을 악하다 하는 그 두 사람은 다 여호와께 미움을 받느니라. 미련한 자는 지혜를 사모할 마음이 없거니 손에 값을 가지고도 무엇을 하랴. 친구는 사랑이 끊이지 아니하고 형제는 위급한 때를 위하여 났느니라. 지혜 없는 자는 남의 손을 잡고 그의 이웃 앞에서 보증이 되느니라.',
    ctxEn:'These are short, standalone wisdom sayings collected in Proverbs. Verse 17 sits among contrasts between the wise and the foolish, lifting up friendship that stays constant — especially when trouble comes.',
    ctxKo:'이 부분은 잠언에 모인 짧고 독립적인 지혜의 교훈들입니다. 17절은 지혜로운 자와 어리석은 자를 대조하는 가운데, 특히 어려움이 닥칠 때 변함없이 지속되는 우정을 높이 말합니다.',
    keyEn:['True friendship is steady, not conditional.','Love is shown most clearly in difficult times.','A faithful companion can become like family in adversity.'],
    keyKo:['진정한 우정은 상황에 따라 변하지 않습니다.','사랑은 어려운 때에 더 분명히 드러납니다.','신실한 동행은 고난 속에서 가족 같은 힘이 될 수 있습니다.'] },
  v02:{ pRefEn:'Proverbs 27:17–19', pRefKo:'잠언 27:17–19',
    pEn:'As iron sharpens iron, so one person sharpens another. The one who guards a fig tree will eat its fruit, and whoever protects their master will be honored. As water reflects the face, so one’s life reflects the heart.',
    pKo:'철이 철을 날카롭게 하는 것 같이 사람이 그의 친구의 얼굴을 빛나게 하느니라. 무화과나무를 지키는 자는 그 과실을 먹고 자기 주인에게 시중드는 자는 영화를 얻느니라. 물에 비치면 얼굴이 서로 같은 것 같이 사람의 마음도 서로 비치느니라.',
    ctxEn:'A cluster of proverbs about relationships and care. The image of iron on iron pictures how honest friends shape and strengthen each other over time.',
    ctxKo:'관계와 돌봄에 관한 잠언 묶음입니다. 철이 철을 가는 이미지는, 정직한 친구가 서로를 다듬고 시간이 지나며 더 강하게 한다는 것을 그려줍니다.',
    keyEn:['Honest friends make each other better.','Growth often happens through close relationships.','Sharpening can involve healthy friction, not just comfort.'],
    keyKo:['정직한 친구는 서로를 더 낫게 합니다.','성장은 종종 가까운 관계 속에서 일어납니다.','다듬어짐에는 편안함만이 아니라 건강한 마찰도 따릅니다.'] },
  v03:{ pRefEn:'Ecclesiastes 4:9–12', pRefKo:'전도서 4:9–12',
    pEn:'Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up. But pity anyone who falls and has no one to help them up. Also, if two lie down together, they will keep warm. But how can one keep warm alone? Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.',
    pKo:'두 사람이 한 사람보다 나음은 그들이 수고함으로 좋은 상을 얻을 것임이라. 혹시 그들이 넘어지면 하나가 그 동무를 붙들어 일으키려니와 홀로 있어 넘어지고 붙들어 일으킬 자가 없는 자에게는 화가 있으리라. 또 두 사람이 함께 누우면 따뜻하거니와 한 사람이면 어찌 따뜻하랴. 한 사람이면 패하겠거니와 두 사람이면 맞설 수 있나니 세 겹줄은 쉽게 끊어지지 아니하느니라.',
    ctxEn:'The Teacher in Ecclesiastes reflects on the emptiness of working only for oneself, and turns to the practical and emotional strength found in companionship.',
    ctxKo:'전도서의 설교자는 자신만을 위해 수고하는 삶의 헛됨을 묵상하다가, 동행 속에서 발견되는 실제적이고 정서적인 힘으로 시선을 돌립니다.',
    keyEn:['We are made for companionship, not isolation.','Friends help us up when we fall.','Shared strength endures what one person cannot.'],
    keyKo:['우리는 고립이 아니라 동행을 위해 지어졌습니다.','친구는 우리가 넘어질 때 일으켜 줍니다.','함께한 힘은 혼자서는 견딜 수 없는 것을 견뎌냅니다.'] },
  v04:{ pRefEn:'1 Corinthians 13:4–7', pRefKo:'고린도전서 13:4–7',
    pEn:'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.',
    pKo:'사랑은 오래 참고 사랑은 온유하며 시기하지 아니하며 사랑은 자랑하지 아니하며 교만하지 아니하며 무례히 행하지 아니하며 자기의 유익을 구하지 아니하며 성내지 아니하며 악한 것을 생각하지 아니하며 불의를 기뻐하지 아니하며 진리와 함께 기뻐하고 모든 것을 참으며 모든 것을 믿으며 모든 것을 바라며 모든 것을 견디느니라.',
    ctxEn:'Paul writes to a divided church that prized impressive gifts. He insists that love — patient and unself-seeking — is what gives everything else its meaning.',
    ctxKo:'바울은 인상적인 은사를 자랑하던 분열된 교회에 편지합니다. 그는 오래 참고 자기 유익을 구하지 않는 사랑이야말로 다른 모든 것에 의미를 주는 것이라고 강조합니다.',
    keyEn:['Love is defined by patience and kindness, not feeling alone.','Real love is not self-seeking.','Love protects, trusts, hopes, and endures.'],
    keyKo:['사랑은 감정만이 아니라 오래 참음과 친절로 정의됩니다.','참된 사랑은 자기 유익을 구하지 않습니다.','사랑은 보호하고 믿고 바라며 견딥니다.'] },
  v05:{ pRefEn:'1 John 4:7–11', pRefKo:'요한일서 4:7–11',
    pEn:'Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God. Whoever does not love does not know God, because God is love. This is how God showed his love among us: He sent his one and only Son into the world that we might live through him.',
    pKo:'사랑하는 자들아 우리가 서로 사랑하자 사랑은 하나님께 속한 것이니 사랑하는 자마다 하나님으로부터 나서 하나님을 알고 사랑하지 아니하는 자는 하나님을 알지 못하나니 이는 하나님은 사랑이심이라. 하나님의 사랑이 우리에게 이렇게 나타난 바 되었으니 하나님이 자기의 독생자를 세상에 보내심은 그로 말미암아 우리를 살리려 하심이라.',
    ctxEn:'John urges a community to love one another, grounding that call not in willpower but in the nature of God, who is love and loved first.',
    ctxKo:'요한은 한 공동체에게 서로 사랑할 것을 권하며, 그 부르심을 의지가 아니라 먼저 사랑하신 사랑이신 하나님의 본성에 뿌리내립니다.',
    keyEn:['Love for others flows from God’s love for us.','To know God is to love.','We love because we were first loved.'],
    keyKo:['타인을 향한 사랑은 우리를 향한 하나님의 사랑에서 흘러나옵니다.','하나님을 안다는 것은 곧 사랑하는 것입니다.','우리가 먼저 사랑받았기에 우리도 사랑합니다.'] },
  v06:{ pRefEn:'Colossians 3:12–14', pRefKo:'골로새서 3:12–14',
    pEn:'Therefore, as God’s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you. And over all these virtues put on love, which binds them all together in perfect unity.',
    pKo:'그러므로 너희는 하나님이 택하사 거룩하고 사랑 받는 자처럼 긍휼과 자비와 겸손과 온유와 오래 참음을 옷 입고 누가 누구에게 불만이 있거든 서로 용납하여 피차 용서하되 주께서 너희를 용서하신 것 같이 너희도 그리하고 이 모든 것 위에 사랑을 더하라 이는 온전하게 매는 띠니라.',
    ctxEn:'Paul describes the new life of a community, listing virtues to “put on” like clothing — and names love as the belt that holds them all together.',
    ctxKo:'바울은 한 공동체의 새로운 삶을 묘사하며, 옷처럼 “입어야” 할 덕목들을 나열하고, 그 모두를 하나로 묶는 띠로 사랑을 지목합니다.',
    keyEn:['Love holds every other virtue together.','Selfless love is something we choose and put on.','Forgiveness and kindness flow from being loved by God.'],
    keyKo:['사랑은 다른 모든 덕목을 하나로 묶습니다.','자기를 내어주는 사랑은 우리가 선택해 입는 것입니다.','용서와 친절은 하나님께 사랑받음에서 흘러나옵니다.'] },
  v07:{ pRefEn:'Joshua 24:14–15', pRefKo:'여호수아 24:14–15',
    pEn:'Now fear the Lord and serve him with all faithfulness. Throw away the gods your ancestors worshiped beyond the Euphrates and in Egypt, and serve the Lord. But if serving the Lord seems undesirable to you, then choose for yourselves this day whom you will serve... But as for me and my household, we will serve the Lord.',
    pKo:'그러므로 이제는 여호와를 경외하며 온전함과 진실함으로 그를 섬기라. 너희의 조상들이 강 저쪽과 애굽에서 섬기던 신들을 치워 버리고 여호와만 섬기라. 만일 여호와를 섬기는 것이 너희에게 좋지 않게 보이거든 너희가 섬길 자를 오늘 택하라... 오직 나와 내 집은 여호와를 섬기겠노라.',
    ctxEn:'At the end of his life, Joshua gathers Israel and calls them to choose whom they will serve. His own household’s commitment becomes a model of family faith.',
    ctxKo:'생의 마지막에 여호수아는 이스라엘을 모으고 누구를 섬길지 택하라고 부릅니다. 그의 집안의 헌신은 가정 신앙의 본보기가 됩니다.',
    keyEn:['Faith is lived out in the home.','Serving God is a daily, deliberate choice.','A household can be shaped by shared commitment.'],
    keyKo:['신앙은 가정 안에서 살아냅니다.','하나님을 섬기는 것은 매일의 의도적인 선택입니다.','가정은 함께한 헌신으로 빚어질 수 있습니다.'] },
  v08:{ pRefEn:'Proverbs 22:6–9', pRefKo:'잠언 22:6–9',
    pEn:'Start children off on the way they should go, and even when they are old they will not turn from it. The rich rule over the poor, and the borrower is slave to the lender. Whoever sows injustice reaps calamity... The generous will themselves be blessed, for they share their food with the poor.',
    pKo:'마땅히 행할 길을 아이에게 가르치라 그리하면 늙어도 그것을 떠나지 아니하리라. 부자는 가난한 자를 주관하고 빚진 자는 채주의 종이 되느니라. 악을 뿌리는 자는 재앙을 거두리니... 선한 눈을 가진 자는 복을 받으리니 이는 양식을 가난한 자에게 줌이니라.',
    ctxEn:'A wisdom saying about parenting set among proverbs on justice and generosity. Early, patient guidance shapes a life that lasts.',
    ctxKo:'정의와 너그러움에 관한 잠언들 가운데 놓인 양육에 관한 지혜의 말씀입니다. 이른 시기의 인내하는 가르침이 오래 지속되는 삶을 빚습니다.',
    keyEn:['Early guidance shapes a lasting direction.','Family care is patient and long-term.','What we teach at home echoes for years.'],
    keyKo:['이른 시기의 가르침이 오래가는 방향을 빚습니다.','가족의 돌봄은 인내하며 오래 이어집니다.','가정에서 가르친 것은 여러 해 동안 울립니다.'] },
  v09:{ pRefEn:'Psalm 127:1–4', pRefKo:'시편 127:1–4',
    pEn:'Unless the Lord builds the house, the builders labor in vain. Unless the Lord watches over the city, the guards stand watch in vain. In vain you rise early and stay up late, toiling for food to eat—for he grants sleep to those he loves. Children are a heritage from the Lord, offspring a reward from him.',
    pKo:'여호와께서 집을 세우지 아니하시면 세우는 자의 수고가 헛되며 여호와께서 성을 지키지 아니하시면 파수꾼의 깨어 있음이 헛되도다. 너희가 일찍이 일어나고 늦게 누우며 수고의 떡을 먹음이 헛되도다 그러므로 여호와께서 그의 사랑하시는 자에게는 잠을 주시는도다. 보라 자식들은 여호와의 기업이요 태의 열매는 그의 상급이로다.',
    ctxEn:'A psalm about trusting God rather than anxious striving. Within that trust, children and family are received as a gift and heritage, not an achievement.',
    ctxKo:'염려하며 애쓰기보다 하나님을 신뢰하는 것에 관한 시편입니다. 그 신뢰 안에서 자녀와 가정은 성취가 아니라 선물이자 기업으로 받아들여집니다.',
    keyEn:['Family is a gift, not a personal achievement.','Trusting God frees us from anxious striving.','Children are received as a heritage and reward.'],
    keyKo:['가정은 개인의 성취가 아니라 선물입니다.','하나님을 신뢰함은 염려하는 수고에서 우리를 자유케 합니다.','자녀는 기업이자 상급으로 받아들여집니다.'] },
  v10:{ pRefEn:'Isaiah 40:28–31', pRefKo:'이사야 40:28–31',
    pEn:'Do you not know? Have you not heard? The Lord is the everlasting God... He gives strength to the weary and increases the power of the weak. Even youths grow tired and weary, and young men stumble and fall; but those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.',
    pKo:'너는 알지 못하였느냐 듣지 못하였느냐 영원하신 하나님 여호와... 피곤한 자에게는 능력을 주시며 무능한 자에게는 힘을 더하시나니 소년이라도 피곤하며 곤비하며 장정이라도 넘어지며 자빠지되 오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리가 날개치며 올라감 같을 것이요 달음박질하여도 곤비하지 아니하겠고 걸어가도 피곤하지 아니하리로다.',
    ctxEn:'Isaiah speaks to a weary, discouraged people. The strength promised here is not self-generated willpower but renewal that comes from waiting on God.',
    ctxKo:'이사야는 지치고 낙심한 백성에게 말합니다. 여기서 약속된 힘은 스스로 만들어낸 의지가 아니라, 하나님을 앙망함에서 오는 새로워짐입니다.',
    keyEn:['Renewed strength comes from hoping in God, not striving alone.','Even the strong grow tired; God meets the weary.','Endurance is sustained from beyond ourselves.'],
    keyKo:['새 힘은 혼자 애씀이 아니라 하나님을 앙망함에서 옵니다.','강한 자도 지치지만, 하나님은 지친 자를 만나주십니다.','견딤은 우리 너머에서 공급됩니다.'] },
  v11:{ pRefEn:'Philippians 4:10–13', pRefKo:'빌립보서 4:10–13',
    pEn:'I rejoiced greatly in the Lord that at last you renewed your concern for me... I have learned to be content whatever the circumstances. I know what it is to be in need, and I know what it is to have plenty... I can do all this through him who gives me strength.',
    pKo:'내가 주 안에서 크게 기뻐함은 너희가 나를 생각하던 것이 이제 다시 싹이 남이니... 어떠한 형편에든지 나는 자족하기를 배웠노니 나는 비천에 처할 줄도 알고 풍부에 처할 줄도 알아... 내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.',
    ctxEn:'Paul writes from hardship, even prison. He is not claiming he can achieve any goal, but that he has learned contentment and strength through Christ in every circumstance.',
    ctxKo:'바울은 어려움, 심지어 감옥에서 이 편지를 씁니다. 그는 어떤 목표든 이룰 수 있다는 것이 아니라, 모든 형편에서 그리스도를 통해 자족과 힘을 배웠다고 말합니다.',
    keyEn:['Strength here means contentment in every circumstance.','It is not about achieving any goal, but trusting Christ.','Endurance comes from a source beyond ourselves.'],
    keyKo:['여기서 힘은 모든 형편에서의 자족을 뜻합니다.','어떤 목표를 이루는 것이 아니라 그리스도를 신뢰하는 것입니다.','견딤은 우리 너머의 근원에서 옵니다.'] },
  v12:{ pRefEn:'Joshua 1:7–9', pRefKo:'여호수아 1:7–9',
    pEn:'Be strong and very courageous. Be careful to obey all the law my servant Moses gave you... Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.',
    pKo:'오직 강하고 극히 담대하여 나의 종 모세가 네게 명령한 그 율법을 다 지켜 행하고... 내가 네게 명령한 것이 아니냐 강하고 담대하라 두려워하지 말며 놀라지 말라 네가 어디로 가든지 네 하나님 여호와가 너와 함께 하느니라.',
    ctxEn:'God commissions Joshua to lead Israel into a daunting new land. The call to courage is grounded in a promise: God’s presence goes with him.',
    ctxKo:'하나님은 여호수아에게 두려운 새 땅으로 이스라엘을 이끌라고 위임하십니다. 담대하라는 부르심은 하나님이 함께하신다는 약속에 뿌리내립니다.',
    keyEn:['Courage is commanded and grounded in God’s presence.','We can keep going because we are not alone.','Fear is met by the promise “I am with you.”'],
    keyKo:['담대함은 명령이자 하나님의 임재에 근거합니다.','우리는 혼자가 아니기에 계속 나아갈 수 있습니다.','두려움은 “내가 너와 함께한다”는 약속으로 마주합니다.'] },
  v13:{ pRefEn:'Proverbs 3:5–8', pRefKo:'잠언 3:5–8',
    pEn:'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight. Do not be wise in your own eyes; fear the Lord and shun evil. This will bring health to your body and nourishment to your bones.',
    pKo:'너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라 너는 범사에 그를 인정하라 그리하면 네 길을 지도하시리라 스스로 지혜롭게 여기지 말지어다 여호와를 경외하며 악을 떠날지어다 이것이 네 몸에 양약이 되어 네 골수를 윤택하게 하리라.',
    ctxEn:'A father’s wisdom to a child: trust that reaches beyond our own limited understanding, and lets God direct the path rather than insisting on our own.',
    ctxKo:'자녀를 향한 아버지의 지혜입니다. 우리의 제한된 명철을 넘어서는 신뢰로, 우리 고집이 아니라 하나님이 길을 인도하시게 하라는 것입니다.',
    keyEn:['Trust reaches beyond our own understanding.','Faith means letting God direct our path.','Trust is whole-hearted, not partial.'],
    keyKo:['신뢰는 우리의 명철을 넘어섭니다.','믿음은 하나님이 우리 길을 인도하시게 하는 것입니다.','신뢰는 부분이 아니라 마음을 다한 것입니다.'] },
  v14:{ pRefEn:'Hebrews 11:1–3', pRefKo:'히브리서 11:1–3',
    pEn:'Now faith is confidence in what we hope for and assurance about what we do not see. This is what the ancients were commended for. By faith we understand that the universe was formed at God’s command, so that what is seen was not made out of what was visible.',
    pKo:'믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니 선진들이 이로써 증거를 얻었느니라 믿음으로 모든 세계가 하나님의 말씀으로 지어진 줄을 우리가 아나니 보이는 것은 나타난 것으로 말미암아 된 것이 아니니라.',
    ctxEn:'The writer opens a famous chapter on faith by defining it: confidence and assurance about what cannot yet be seen, then points to a long line of people who lived by it.',
    ctxKo:'저자는 믿음에 관한 유명한 장을 그 정의로 엽니다. 아직 볼 수 없는 것에 대한 확신과 증거라고 말한 뒤, 그렇게 살아온 사람들의 긴 행렬을 가리킵니다.',
    keyEn:['Faith is assurance about what we cannot yet see.','Belief steadies us before the outcome is visible.','We stand in a long line of people who trusted God.'],
    keyKo:['믿음은 아직 볼 수 없는 것에 대한 확신입니다.','믿음은 결과가 보이기 전에 우리를 붙들어 줍니다.','우리는 하나님을 신뢰해 온 긴 행렬 안에 서 있습니다.'] },
  v15:{ pRefEn:'2 Corinthians 5:6–8', pRefKo:'고린도후서 5:6–8',
    pEn:'Therefore we are always confident and know that as long as we are at home in the body we are away from the Lord. For we live by faith, not by sight. We are confident, I say, and would prefer to be away from the body and at home with the Lord.',
    pKo:'그러므로 우리가 항상 담대하여 몸으로 있을 때에는 주와 따로 있는 줄을 아노니 이는 우리가 믿음으로 행하고 보는 것으로 행하지 아니함이로라 우리가 담대하여 원하는 바는 차라리 몸을 떠나 주와 함께 있는 그것이라.',
    ctxEn:'Paul speaks of living with confidence amid uncertainty and weakness, anchored in trust rather than what the eyes can currently confirm.',
    ctxKo:'바울은 불확실함과 연약함 가운데서도 담대히 사는 것에 대해 말하며, 지금 눈으로 확인할 수 있는 것이 아니라 신뢰에 닻을 내립니다.',
    keyEn:['We walk by faith, not by sight.','Confidence can hold even when outcomes are unseen.','Trust steadies us in uncertainty.'],
    keyKo:['우리는 보는 것이 아니라 믿음으로 행합니다.','담대함은 결과가 보이지 않을 때에도 지속될 수 있습니다.','신뢰는 불확실함 속에서 우리를 붙들어 줍니다.'] },
  v16:{ pRefEn:'Colossians 3:12–14', pRefKo:'골로새서 3:12–14',
    pEn:'Clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you. And over all these virtues put on love.',
    pKo:'긍휼과 자비와 겸손과 온유와 오래 참음을 옷 입고 누가 누구에게 불만이 있거든 서로 용납하여 피차 용서하되 주께서 너희를 용서하신 것 같이 너희도 그리하고 이 모든 것 위에 사랑을 더하라.',
    ctxEn:'In describing a community’s new life, Paul roots forgiveness in a memory: forgive because, and as, you have been forgiven by the Lord.',
    ctxKo:'한 공동체의 새로운 삶을 묘사하며, 바울은 용서를 한 기억에 뿌리내립니다. 주께 용서받았기에, 그리고 그처럼 용서하라는 것입니다.',
    keyEn:['We forgive because we have first been forgiven.','Letting go is part of healing.','Grace toward others grows from grace received.'],
    keyKo:['우리는 먼저 용서받았기에 용서합니다.','내려놓음은 회복의 일부입니다.','타인을 향한 은혜는 받은 은혜에서 자랍니다.'] },
  v17:{ pRefEn:'Ephesians 4:31–32', pRefKo:'에베소서 4:31–32',
    pEn:'Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice. Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.',
    pKo:'너희는 모든 악독과 노함과 분냄과 떠드는 것과 비방하는 것을 모든 악의와 함께 버리고 서로 친절하게 하며 불쌍히 여기며 서로 용서하기를 하나님이 그리스도 안에서 너희를 용서하심과 같이 하라.',
    ctxEn:'Paul contrasts a life weighed down by bitterness with one freed by kindness and forgiveness — the kind of forgiveness already received in Christ.',
    ctxKo:'바울은 쓴 뿌리에 짓눌린 삶과, 친절과 용서로 자유로워진 삶을 대조합니다. 곧 그리스도 안에서 이미 받은 그 용서입니다.',
    keyEn:['Releasing anger makes room for healing.','Kindness and mercy go together with forgiveness.','We forgive as we have been forgiven.'],
    keyKo:['분노를 내려놓음은 회복의 자리를 만듭니다.','친절과 자비는 용서와 함께 갑니다.','우리는 용서받은 대로 용서합니다.'] },
  v18:{ pRefEn:'Matthew 6:12–15', pRefKo:'마태복음 6:12–15',
    pEn:'And forgive us our debts, as we also have forgiven our debtors... For if you forgive other people when they sin against you, your heavenly Father will also forgive you. But if you do not forgive others their sins, your Father will not forgive your sins.',
    pKo:'우리가 우리에게 죄 지은 자를 사하여 준 것 같이 우리 죄를 사하여 주시옵고... 너희가 사람의 잘못을 용서하면 너희 하늘 아버지께서도 너희 잘못을 용서하시려니와 너희가 사람의 잘못을 용서하지 아니하면 너희 아버지께서도 너희 잘못을 용서하지 아니하시리라.',
    ctxEn:'Part of the Lord’s Prayer that Jesus taught. Forgiving others and being forgiven are tied closely together — mercy received and mercy given flow as one.',
    ctxKo:'예수께서 가르치신 주기도문의 일부입니다. 남을 용서하는 것과 용서받는 것은 긴밀히 연결되어, 받은 자비와 베푸는 자비가 하나로 흐릅니다.',
    keyEn:['Forgiving and being forgiven are deeply connected.','Mercy given flows from mercy received.','Letting go frees us, not only the other person.'],
    keyKo:['용서하는 것과 용서받는 것은 깊이 연결됩니다.','베푸는 자비는 받은 자비에서 흘러나옵니다.','내려놓음은 상대뿐 아니라 우리도 자유케 합니다.'] },
  v19:{ pRefEn:'1 Thessalonians 5:16–18', pRefKo:'데살로니가전서 5:16–18',
    pEn:'Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.',
    pKo:'항상 기뻐하라 쉬지 말고 기도하라 범사에 감사하라 이것이 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라.',
    ctxEn:'A short string of encouragements closing Paul’s letter. Thanks “in all circumstances” is not pretending all is well, but choosing gratitude even within hardship.',
    ctxKo:'바울의 편지를 맺는 짧은 권면의 묶음입니다. “범사에” 감사하라는 것은 모든 것이 괜찮은 척하라는 것이 아니라, 어려움 속에서도 감사를 택하라는 것입니다.',
    keyEn:['Gratitude is a choice, even in hard circumstances.','Thankfulness is woven into a praying life.','We notice grace rather than only what is missing.'],
    keyKo:['감사는 어려운 형편 속에서도 택하는 것입니다.','감사는 기도하는 삶 속에 엮여 있습니다.','우리는 부족한 것만이 아니라 은혜를 알아차립니다.'] },
  v20:{ pRefEn:'Psalm 118:22–24', pRefKo:'시편 118:22–24',
    pEn:'The stone the builders rejected has become the cornerstone; the Lord has done this, and it is marvelous in our eyes. The Lord has done it this very day; let us rejoice today and be glad.',
    pKo:'건축자가 버린 돌이 집 모퉁이의 머릿돌이 되었나니 이는 여호와께서 행하신 것이요 우리 눈에 기이한 바로다 이 날은 여호와께서 정하신 것이라 이 날에 우리가 즐거워하고 기뻐하리로다.',
    ctxEn:'A psalm of thanksgiving for rescue. Verse 24 receives the present day itself as a gift made by God, calling for gladness right now.',
    ctxKo:'구원을 인한 감사의 시편입니다. 24절은 오늘이라는 날 자체를 하나님이 만드신 선물로 받아들이며, 바로 지금 기뻐하라고 부릅니다.',
    keyEn:['Today itself is a gift from God.','Gratitude can begin with the present moment.','Joy is a response to grace already given.'],
    keyKo:['오늘이라는 날 자체가 하나님의 선물입니다.','감사는 지금 이 순간에서 시작될 수 있습니다.','기쁨은 이미 주어진 은혜에 대한 응답입니다.'] },
  v21:{ pRefEn:'Psalm 100:1–5', pRefKo:'시편 100:1–5',
    pEn:'Shout for joy to the Lord, all the earth. Worship the Lord with gladness; come before him with joyful songs... Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name. For the Lord is good and his love endures forever.',
    pKo:'온 땅이여 여호와께 즐거운 찬송을 부를지어다 기쁨으로 여호와를 섬기며 노래하면서 그의 앞에 나아갈지어다... 감사함으로 그의 문에 들어가며 찬송함으로 그의 궁정에 들어가서 그에게 감사하며 그의 이름을 송축할지어다 여호와는 선하시니 그의 인자하심이 영원하고.',
    ctxEn:'A psalm inviting all the earth into worship. Thanksgiving is the doorway — we come into God’s presence through gratitude and praise.',
    ctxKo:'온 땅을 예배로 초청하는 시편입니다. 감사는 문입니다 — 우리는 감사와 찬송을 통해 하나님의 임재로 나아갑니다.',
    keyEn:['Thanksgiving is the doorway into worship.','Gratitude rests on God’s enduring goodness.','Praise turns our attention from self to God.'],
    keyKo:['감사는 예배로 들어가는 문입니다.','감사는 하나님의 영원한 선하심에 근거합니다.','찬송은 우리의 시선을 자기에서 하나님께로 돌립니다.'] },
  v22:{ pRefEn:'Jeremiah 29:10–14', pRefKo:'예레미야 29:10–14',
    pEn:'“For I know the plans I have for you,” declares the Lord, “plans to prosper you and not to harm you, plans to give you hope and a future. Then you will call on me and come and pray to me, and I will listen to you. You will seek me and find me when you seek me with all your heart.”',
    pKo:'여호와의 말씀이니라 너희를 향한 나의 생각을 내가 아나니 평안이요 재앙이 아니니라 너희에게 미래와 희망을 주는 것이니라 너희가 내게 부르짖으며 내게 와서 기도하면 내가 너희들의 기도를 들을 것이요 너희가 온 마음으로 나를 구하면 나를 찾을 것이요 나를 만나리라.',
    ctxEn:'God speaks to people in exile, far from home, telling them their displacement is not the end. The promise of a future is given to those in a long, hard wait.',
    ctxKo:'하나님은 고향에서 멀리 떠난 포로된 백성에게 말씀하시며, 그들의 처지가 끝이 아니라고 하십니다. 미래에 대한 약속은 길고 힘든 기다림 가운데 있는 자들에게 주어집니다.',
    keyEn:['God’s good plans hold even in seasons of waiting.','Hope is given to people in the middle of hardship.','The story is not over yet.'],
    keyKo:['하나님의 선한 계획은 기다림의 때에도 지속됩니다.','소망은 고난의 한가운데 있는 자들에게 주어집니다.','이야기는 아직 끝나지 않았습니다.'] },
  v23:{ pRefEn:'Romans 15:13', pRefKo:'로마서 15:13',
    pEn:'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.',
    pKo:'소망의 하나님이 모든 기쁨과 평강을 믿음 안에서 너희에게 충만하게 하사 성령의 능력으로 소망이 넘치게 하시기를 원하노라.',
    ctxEn:'Paul closes a section with a blessing. Hope here is not wishful thinking but something God fills us with as we trust — overflowing by his Spirit.',
    ctxKo:'바울은 한 단락을 축복으로 맺습니다. 여기서 소망은 막연한 바람이 아니라, 우리가 신뢰할 때 하나님이 채워주시는 것으로, 성령으로 넘쳐흐릅니다.',
    keyEn:['Hope is something God fills us with as we trust.','Joy and peace accompany real hope.','Hope can overflow, not just barely survive.'],
    keyKo:['소망은 우리가 신뢰할 때 하나님이 채워주시는 것입니다.','기쁨과 평강은 참된 소망과 함께합니다.','소망은 겨우 버티는 것이 아니라 넘쳐흐를 수 있습니다.'] },
  v24:{ pRefEn:'Romans 8:28–30', pRefKo:'로마서 8:28–30',
    pEn:'And we know that in all things God works for the good of those who love him, who have been called according to his purpose. For those God foreknew he also predestined to be conformed to the image of his Son...',
    pKo:'우리가 알거니와 하나님을 사랑하는 자 곧 그의 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라 하나님이 미리 아신 자들을 또한 그 아들의 형상을 본받게 하기 위하여 미리 정하셨으니...',
    ctxEn:'Paul writes to people facing suffering. The promise is not that everything is good, but that God is at work weaving even hard things toward good.',
    ctxKo:'바울은 고난을 마주한 사람들에게 씁니다. 약속은 모든 것이 좋다는 것이 아니라, 하나님이 어려운 일까지도 선을 향해 엮어가고 계신다는 것입니다.',
    keyEn:['God works through all things, even hard ones, toward good.','This is trust, not a promise that all is painless.','Hope rests on God’s purpose, not our circumstances.'],
    keyKo:['하나님은 어려운 일까지 포함한 모든 것을 통해 선을 이루십니다.','이것은 고통이 없다는 약속이 아니라 신뢰입니다.','소망은 우리 형편이 아니라 하나님의 뜻에 근거합니다.'] },
  v25:{ pRefEn:'Proverbs 3:5–6', pRefKo:'잠언 3:5–6',
    pEn:'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',
    pKo:'너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라 너는 범사에 그를 인정하라 그리하면 네 길을 지도하시리라.',
    ctxEn:'A foundational proverb on wisdom: real discernment begins not with our own cleverness, but with acknowledging God in every decision and direction.',
    ctxKo:'지혜에 관한 기초가 되는 잠언입니다. 참된 분별은 우리의 영리함이 아니라, 모든 결정과 방향에서 하나님을 인정하는 데서 시작됩니다.',
    keyEn:['Wisdom begins with acknowledging God, not self.','Discernment trusts beyond our own understanding.','Right paths come from submitting our ways to God.'],
    keyKo:['지혜는 자기가 아니라 하나님을 인정하는 데서 시작됩니다.','분별은 우리의 명철을 넘어 신뢰합니다.','바른 길은 우리 길을 하나님께 맡기는 데서 옵니다.'] },
  v26:{ pRefEn:'James 1:5–8', pRefKo:'야고보서 1:5–8',
    pEn:'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you. But when you ask, you must believe and not doubt, because the one who doubts is like a wave of the sea, blown and tossed by the wind.',
    pKo:'너희 중에 누구든지 지혜가 부족하거든 모든 사람에게 후히 주시고 꾸짖지 아니하시는 하나님께 구하라 그리하면 주시리라 오직 믿음으로 구하고 조금도 의심하지 말라 의심하는 자는 마치 바람에 밀려 요동하는 바다 물결 같으니.',
    ctxEn:'James, writing to people facing trials, says wisdom is not earned by cleverness but asked for — and God gives it generously, without scolding.',
    ctxKo:'시련을 마주한 사람들에게 쓰는 야고보는, 지혜는 영리함으로 얻는 것이 아니라 구하는 것이며, 하나님은 꾸짖지 않으시고 후히 주신다고 말합니다.',
    keyEn:['Wisdom is asked for, not just achieved.','God gives generously, without scolding.','We seek wisdom with trust rather than doubt.'],
    keyKo:['지혜는 단지 성취가 아니라 구하는 것입니다.','하나님은 꾸짖지 않으시고 후히 주십니다.','우리는 의심이 아니라 신뢰로 지혜를 구합니다.'] },
  v27:{ pRefEn:'Proverbs 4:5–7', pRefKo:'잠언 4:5–7',
    pEn:'Get wisdom, get understanding; do not forget my words or turn away from them. Do not forsake wisdom, and she will protect you; love her, and she will watch over you. The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding.',
    pKo:'지혜를 얻으며 명철을 얻으라 내 입의 말을 잊지 말며 어기지 말라 지혜를 버리지 말라 그가 너를 보호하리라 그를 사랑하라 그가 너를 지키리라 지혜가 제일이니 지혜를 얻으라 네가 얻은 모든 것을 가지고 명철을 얻을지니라.',
    ctxEn:'A father urges his child to pursue wisdom above all else, treating it as worth more than any possession — a lifelong, deliberate pursuit.',
    ctxKo:'아버지는 자녀에게 무엇보다 지혜를 추구하라고 권하며, 그것을 어떤 소유보다 값진 것으로 여깁니다 — 평생에 걸친 의도적인 추구입니다.',
    keyEn:['Wisdom is worth pursuing above possessions.','Seeking understanding is a lifelong, deliberate choice.','Wisdom protects and guides those who love it.'],
    keyKo:['지혜는 소유보다 추구할 가치가 있습니다.','명철을 구함은 평생에 걸친 의도적 선택입니다.','지혜는 그를 사랑하는 자를 보호하고 인도합니다.'] },
};

// merge category pack + verse pack into a full guide for a verse
function vbStudyGuide(verseId) {
  const v = window.vbVerse ? window.vbVerse(verseId) : null;
  const vp = VB_STUDY_VERSE[verseId];
  if (!v || !vp) return null;
  const cp = VB_STUDY_CAT[v.cat] || VB_STUDY_CAT.hope;
  return { verse:v, ...vp, ...cp };
}

Object.assign(window, { VB_STUDY_CAT, VB_STUDY_VERSE, vbStudyGuide });
